name: SonarCloud
on:
  push:
    branches:
      - master
      - ci
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-22.04
    env:
      BUILD_WRAPPER_OUT_DIR: /home/runner/work/xmoto/xmoto/build # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install sonar-scanner and build-wrapper
        run: |
          curl -sSLo /tmp/bw.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -q /tmp/bw.zip -d /usr/local
          SONAR_VERSION=7.0.2.4839
          curl -sSLo /tmp/ss.zip \
            "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux-x64.zip"
          unzip -q /tmp/ss.zip -d /usr/local
          echo "/usr/local/sonar-scanner-${SONAR_VERSION}-linux-x64/bin" >> $GITHUB_PATH
          echo "/usr/local/build-wrapper-linux-x86" >> $GITHUB_PATH
      - name: Install dependencies
        run: ./.github/workflows/deps/linux.sh
      - name: Configure build
        run: |
          mkdir build
          cd build

          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -G Ninja \
            ..

      - name: Run build-wrapper
        run: |
          cd build
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build .
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
